
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  analytics:
    # Config indicated by + and applies to all files under models/example/
    customers_view:
      +schema: "{{ 'revenue_dev' if target.name == 'dev' else 'revenue' }}"

    orders_stg:
      +schema: "{{ 'revenue_dev' if target.name == 'dev' else 'revenue' }}"

    orderitems_view:
      +schema: "{{ 'revenue_dev' if target.name == 'dev' else 'revenue' }}"

    customerrevenue:
      +schema: "{{ 'revenue_dev' if target.name == 'dev' else 'revenue' }}"
      +materialized: table

    orders_fact:
      +schema: "{{ 'revenue_dev' if target.name == 'dev' else 'revenue' }}"
      +materialized: table

    orderitems_uniq:
      +schema: "{{ 'revenue_dev' if target.name == 'dev' else 'revenue' }}"
      +materialized: table

    revenue_us_macro_test:
      +schema: TRAINING
      +materialized: view
    
    profit_us:
      +schema: TRAINING
      +materialized: view
    
    profit_uk:
      +schema: TRAINING
      +materialized: view

    profit_india:
      +schema: TRAINING
      +materialized: view
