{{ config(materialized='table') }}

WITH CUSTOMERORDER AS (
    SELECT
        C.CUSTOMERID,
        CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
        COUNT(O.ORDERID) AS ORDERCOUNT
    FROM {{ source('stg', 'customers') }} AS C
    INNER JOIN {{ source('stg', 'orders') }} AS O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY ORDERCOUNT DESC
)

SELECT
    CUSTOMERID,
    CUSTOMERNAME,
    ORDERCOUNT
FROM CUSTOMERORDER
